# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      flutter_js_asset|bundle_builder:
        options:

